# Generated by Django 6.0.4 on 2026-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo_notificacion', models.CharField(choices=[('APERTURA_PENDIENTE', 'Apertura Pendiente'), ('CIERRE_PENDIENTE', 'Cierre Pendiente'), ('DIFERENCIA_CAJA', 'Diferencia de Caja'), ('GASTO_ELEVADO', 'Gasto Elevado')], max_length=20)),
                ('fecha_notificacion', models.DateField()),
                ('hora_notificacion', models.TimeField()),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
