# Generated by Django 6.0.4 on 2026-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_notificacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.CharField(max_length=20),
        ),
    ]
