# Generated by Django 6.0.4 on 2026-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apertura', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajadiaria',
            name='id',
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='id_caja',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cajadiaria',
            name='estado_caja',
            field=models.CharField(default='ABIERTA', max_length=10),
        ),
    ]
