# Generated by Django 6.0.4 on 2026-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_negocio', models.EmailField(blank=True, max_length=150, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('monto_inicial_sugerido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('permitir_edicion_movimientos', models.BooleanField(default=True)),
                ('permitir_eliminacion_movimientos', models.BooleanField(default=True)),
                ('limite_diferencia_caja', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
            },
        ),
    ]
