# Generated by Django 6.0.4 on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apertura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id_cierre', models.AutoField(primary_key=True, serialize=False)),
                ('hora_cierre', models.TimeField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_esperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_cierre', models.CharField(max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('caja', models.OneToOneField(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='apertura.cajadiaria')),
            ],
            options={
                'db_table': 'cierre_caja',
            },
        ),
    ]
