# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_real_digital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
