# Generated by Django 6.0.4 on 2026-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='contrasena', max_length=255),
        ),
    ]
