# Generated by Django 6.0.4 on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apertura', '0001_initial'),
        ('usuarios', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimiento',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('tipo_categoria', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categoria_movimiento',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_movimiento', models.DateField()),
                ('hora_movimiento', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='apertura.cajadiaria')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='movimientos.categoriamovimiento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'movimiento_caja',
            },
        ),
    ]
