# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='medio_pago',
            field=models.CharField(default='EFECTIVO', max_length=20),
        ),
    ]
